/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jason' at '11/2/17 11:44 PM' with Gradle 3.2.1
 *
 * @author jason, @date 11/2/17 11:44 PM
 */

import org.joda.time.LocalTime;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        LocalTime currentTime = new LocalTime();
        System.out.println("The current local time is: " + currentTime);

    }
}
